stages:
  - build
  - test
  - codeCoverage
build:
  image: adoptopenjdk:11
  stage: build
  script:
    - ./gradlew bootJar
  artifacts:
    paths:
      - build/libs/*.jar
test:
  image: adoptopenjdk:11
  needs:
    - build
  stage: test
  script:
    ./gradlew test
  artifacts:
    paths:
      - build/test-results/test/*.xml
codeCoverage:
  image: adoptopenjdk:11
  needs:
    - build
    - test
  stage: codeCoverage
  script:
    ./gradlew jacocoTestReport
    ./gradlew jacocoTestCoverageVerification
  allow_failure: true
  artifacts:
    when: always
    paths:
      - build/reports/jacoco/
