apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-kl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-kl
  template:
    metadata:
      labels:
        app: sa-kl
    spec:
      containers:
        - image: registry.gitlab.com/galv-vmw-apr-2021/2-simple-autos/yvonne-keagan:49 
          name: sa-kl
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "$DB_HOST"
            - name: DB_NAME
              value: "$DB_NAME"
            - name: DB_USER
              value: "$DB_USER"
            - name: DB_PWD
              value: "$DB_PWD"
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: simple-autos-deploy
